name: Code Climate Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run tests and collect coverage
      run: |
        npm install jest codeclimate-test-reporter
        npx jest --coverage
        npx codeclimate-test-reporter < coverage/lcov.info

    - name: Upload coverage to Code Climate
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
        ./cc-test-reporter format-coverage -t lcov coverage/lcov.info
        ./cc-test-reporter upload-coverage
        ./cc-test-reporter after-build
